/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/openkruise/agents/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxSetLister helps list SandboxSets.
// All objects returned here must be treated as read-only.
type SandboxSetLister interface {
	// List lists all SandboxSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SandboxSet, err error)
	// SandboxSets returns an object that can list and get SandboxSets.
	SandboxSets(namespace string) SandboxSetNamespaceLister
	SandboxSetListerExpansion
}

// sandboxSetLister implements the SandboxSetLister interface.
type sandboxSetLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SandboxSet]
}

// NewSandboxSetLister returns a new SandboxSetLister.
func NewSandboxSetLister(indexer cache.Indexer) SandboxSetLister {
	return &sandboxSetLister{listers.New[*apiv1alpha1.SandboxSet](indexer, apiv1alpha1.Resource("sandboxset"))}
}

// SandboxSets returns an object that can list and get SandboxSets.
func (s *sandboxSetLister) SandboxSets(namespace string) SandboxSetNamespaceLister {
	return sandboxSetNamespaceLister{listers.NewNamespaced[*apiv1alpha1.SandboxSet](s.ResourceIndexer, namespace)}
}

// SandboxSetNamespaceLister helps list and get SandboxSets.
// All objects returned here must be treated as read-only.
type SandboxSetNamespaceLister interface {
	// List lists all SandboxSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SandboxSet, err error)
	// Get retrieves the SandboxSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.SandboxSet, error)
	SandboxSetNamespaceListerExpansion
}

// sandboxSetNamespaceLister implements the SandboxSetNamespaceLister
// interface.
type sandboxSetNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SandboxSet]
}
