/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/openkruise/agents/api/v1alpha1"
	scheme "github.com/openkruise/agents/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CheckpointsGetter has a method to return a CheckpointInterface.
// A group's client should implement this interface.
type CheckpointsGetter interface {
	Checkpoints(namespace string) CheckpointInterface
}

// CheckpointInterface has methods to work with Checkpoint resources.
type CheckpointInterface interface {
	Create(ctx context.Context, checkpoint *apiv1alpha1.Checkpoint, opts v1.CreateOptions) (*apiv1alpha1.Checkpoint, error)
	Update(ctx context.Context, checkpoint *apiv1alpha1.Checkpoint, opts v1.UpdateOptions) (*apiv1alpha1.Checkpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, checkpoint *apiv1alpha1.Checkpoint, opts v1.UpdateOptions) (*apiv1alpha1.Checkpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Checkpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.CheckpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Checkpoint, err error)
	CheckpointExpansion
}

// checkpoints implements CheckpointInterface
type checkpoints struct {
	*gentype.ClientWithList[*apiv1alpha1.Checkpoint, *apiv1alpha1.CheckpointList]
}

// newCheckpoints returns a Checkpoints
func newCheckpoints(c *ApiV1alpha1Client, namespace string) *checkpoints {
	return &checkpoints{
		gentype.NewClientWithList[*apiv1alpha1.Checkpoint, *apiv1alpha1.CheckpointList](
			"checkpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Checkpoint { return &apiv1alpha1.Checkpoint{} },
			func() *apiv1alpha1.CheckpointList { return &apiv1alpha1.CheckpointList{} },
		),
	}
}
