/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/openkruise/agents/api/v1alpha1"
	scheme "github.com/openkruise/agents/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TrafficPoliciesGetter has a method to return a TrafficPolicyInterface.
// A group's client should implement this interface.
type TrafficPoliciesGetter interface {
	TrafficPolicies(namespace string) TrafficPolicyInterface
}

// TrafficPolicyInterface has methods to work with TrafficPolicy resources.
type TrafficPolicyInterface interface {
	Create(ctx context.Context, trafficPolicy *apiv1alpha1.TrafficPolicy, opts v1.CreateOptions) (*apiv1alpha1.TrafficPolicy, error)
	Update(ctx context.Context, trafficPolicy *apiv1alpha1.TrafficPolicy, opts v1.UpdateOptions) (*apiv1alpha1.TrafficPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, trafficPolicy *apiv1alpha1.TrafficPolicy, opts v1.UpdateOptions) (*apiv1alpha1.TrafficPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.TrafficPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.TrafficPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.TrafficPolicy, err error)
	TrafficPolicyExpansion
}

// trafficPolicies implements TrafficPolicyInterface
type trafficPolicies struct {
	*gentype.ClientWithList[*apiv1alpha1.TrafficPolicy, *apiv1alpha1.TrafficPolicyList]
}

// newTrafficPolicies returns a TrafficPolicies
func newTrafficPolicies(c *ApiV1alpha1Client, namespace string) *trafficPolicies {
	return &trafficPolicies{
		gentype.NewClientWithList[*apiv1alpha1.TrafficPolicy, *apiv1alpha1.TrafficPolicyList](
			"trafficpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.TrafficPolicy { return &apiv1alpha1.TrafficPolicy{} },
			func() *apiv1alpha1.TrafficPolicyList { return &apiv1alpha1.TrafficPolicyList{} },
		),
	}
}
