/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	agentsapiv1alpha1 "gitlab.alibaba-inc.com/serverlessinfra/agents/api/v1alpha1"
	versioned "gitlab.alibaba-inc.com/serverlessinfra/agents/client/clientset/versioned"
	internalinterfaces "gitlab.alibaba-inc.com/serverlessinfra/agents/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "gitlab.alibaba-inc.com/serverlessinfra/agents/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxInformer provides access to a shared informer and lister for
// Sandboxes.
type SandboxInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.SandboxLister
}

type sandboxInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSandboxInformer constructs a new informer for Sandbox type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSandboxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSandboxInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSandboxInformer constructs a new informer for Sandbox type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSandboxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Sandboxes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Sandboxes(namespace).Watch(context.TODO(), options)
			},
		},
		&agentsapiv1alpha1.Sandbox{},
		resyncPeriod,
		indexers,
	)
}

func (f *sandboxInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSandboxInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sandboxInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&agentsapiv1alpha1.Sandbox{}, f.defaultInformer)
}

func (f *sandboxInformer) Lister() apiv1alpha1.SandboxLister {
	return apiv1alpha1.NewSandboxLister(f.Informer().GetIndexer())
}
