POST https://api.e2b-ths.ultramarines.cn/api-keys
Content-Type: application/json
X-API-Key: admin-987654321

{
  "name": "test"
}

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###