### create sandbox
POST https://api.e2b-demo.ultramarines.cn/sandboxes
Content-Type: application/json
X-API-Key: GG

{
  "templateID": "code-interpreter",
  "timeout": 300
}

### run code

POST https://49999-code-interpreter-5c6fffb64b-nbqs9.e2b-yunqi.ultramarines.cn/execute
Content-Type: application/json
X-ACCESS-TOKEN: GG

{
  "code": "print('Hello World!')",
  "language": "python"
}

### resume sandbox

POST https://api.e2b-demo.ultramarines.cn/sandboxes/code-interpreter-58c67749bf-tgmhm/resume
Content-Type: application/json
X-API-Key: c04c7990-c845-4bba-b824-b294acca45e8


### delete sandbox
DELETE https://api.e2b-yunqi.ultramarines.cn/sandboxes/code-interpreter-5c6fffb64b-vbfqh
Content-Type: application/json
X-API-Key: GG

### get debug info
GET https://api.e2b-ths.ultramarines.cn/debug/
Content-Type: application/json
X-API-Key: admin-987654321
