apiVersion: v1
kind: Service
metadata:
  name: sandbox-manager
  namespace: sandbox-system
  labels:
    component: sandbox-manager
    app.kubernetes.io/name: sandbox-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: manager
  selector:
    component: sandbox-manager
    app.kubernetes.io/name: sandbox-manager