name: Build and push commit-job

on:
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      COMMIT_JOB_IMG: openkruise/commit-job:${{ github.ref_name }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.HUB_KRUISE }}
      - name: Build and push the Docker image
        run: |
          docker buildx create --use --platform=linux/amd64,linux/arm64 --name multi-platform-builder
          docker buildx build --platform=linux/amd64,linux/arm64 \
            -f dockerfiles/commit-job.Dockerfile \
            --build-arg NERDCTL_BRANCH=v2.0.0 \
            -t "$COMMIT_JOB_IMG" \
            --push .
